### ISSUE TITLE
Clear todo itens

### ISSUE THREAD

**Issue by stLmpp** [stLmpp/biomercs-api#6]
- [x] Better error message on MapperService.map when there's no MapProfile
- [x] Remove PlatformGameMiniGameModeStageService.findRandom
- [x] Remove PlayerService.findRandom
- [x] Remove ScorePlayerService.addManyRandom
- [x] Remove ScoreController.insertRandom
- [x] Remove ScoreController.insertManyRandom
- [x] Remove ScoreService.insert
- [x] Better error handling for SQL errors in HandleErrorFilter.catch (maybe create a issue for this only alone)

**Comment by stLmpp** [comment]
closed by https://github.com/stLmpp/biomercs-v2-api/pull/14
